@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
@c
@c   Routines
@c
@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc


@c cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

@node    Function Calls , Methods , Distribution Library,      Top
@comment node-name,       next,     previous,                  up

    
The chapter Function calls  contains documentation of 
various functions. 

@cindex Another sample index entry

@menu 
* Methods:: Different methods to generate random numbers
* Stdgen::  Standard generators
* Tests::   Run various statistical tests, check timing...
* Utils::   Auxilliary Subroutines
@end menu

@chapter Function Calls


@c cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

@node    Methods, Arou , Function Calls,      Function Calls
@comment node-name,next, previous,            up

@menu
* Arou::                   Type:continuous univariate random variate 
                           Method:ratio-of uniforms with enveloping polygon
* Cstd::                   Type: continuous univariate random variate
                           Method: generators form standard distribution 
                            (from CRAND)
* Dau::                    Type: discrete random variate
                           Method: alias and alias-urn method
* Dis::                    Type: discrete univariate random variate
                           Method: indexed search (guide table)
* Tabl::                   Type: cantinuous univariate random variate
                           Method: rejection form piecewise constant
                            hat (Ahren´s table method)
* Tdr::                    Type: contiuous univariate random variate
                           Method: transformed density rejection
* Rect::                   Type: continuous multivariate random variate
                           Method: uniformly distributed in rectangle
* Unif::                   Dummy generator, produces uniform random
                            numbers in UNURAN framework
* Utdr::                   Type: continuous univariate random variate
                           Method: transformed density rejection with 
                            three points of contact
* Set::                    Set, change, get parameters for generators
@end menu



@section methods

@c cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

@node    Arou,        Cstd , Methods,     Methods
@comment node-name,   next,  previous,    up

@subsection arou



@deftypefn {Library Function} struct unur_par *unur_arou_new( 
double @var{*pdf}(double @var{x},double @var{*pdf_param}, int @var{n_pdf_params}),                                                                            double @var{*dpdf}(double @var{x},double @var{*pdf_param}, int @var{n_pdf_params}) ) 
...get default parameters for generator             
@end deftypefn

@deftypefn {Library Function} struct unur_gen *unur_arou_init( 
struct unur_par @var{*parameters} )                                            ...initialize new generator                          
@end deftypefn

@deftypefn {Library Function} double unur_arou_sample( 
struct unur_gen @var{*generator} )                                             ...sample from generator
@end deftypefn

@deftypefn {Library Function} double unur_arou_sample_check( 
struct unur_gen @var{*generator} )                                             ...sample from generator                             
@end deftypefn

@deftypefn {Library Function} void unur_arou_free(
struct unur_gen @var{*generator})                                              ...destroy generator object                          
@end deftypefn     


@c cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

@node    Cstd,      Dau , Arou,     Methods
@comment node-name, next, previous, up

@subsection cstd


@deftypefn {Library Function} struct unur_par *unur_cstd_new( 
char @var{*definition} )                                                       ...get default parameters for generator        
@end deftypefn            

@deftypefn {Library Function} struct unur_gen *unur_cstd_init( 
struct unur_par @var{*parameters} )                                            ...initialize new generator
@end deftypefn            

@deftypefn {Library Function} double unur_cstd_sample( 
struct unur_gen @var{*generator} )                                             ...sample from generator
@end deftypefn            

@deftypefn {Library Function} void unur_cstd_free( 
struct unur_gen @var{*generator})                                              ...destroy generator object                          
@end deftypefn            
   


@c cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

@node    Dau,       Dis , Cstd,     Methods
@comment node-name, next, previous, up

@subsection dau


@deftypefn {Library Function} struct unur_par *unur_dau_new( 
double @var{*probabilities}, int @var{plength})
      ...get default parameters for generator              
@end deftypefn     

@deftypefn {Library Function} struct unur_gen *unur_dau_init( 
struct unur_par @var{*parameters} )                                            ...initialize new generator                         
@end deftypefn     

@deftypefn {Library Function} int unur_dau_sample( 
struct unur_gen @var{*generator} )                                             ...sample from generator                             
@end deftypefn     

@deftypefn {Library Function} void unur_dau_free( 
struct unur_gen @var{*generator} )                                             ...destroy generator object                          
@end deftypefn     



@c cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

@node    Dis,       Tabl, Dau,      Methods
@comment node-name, next, previous, up

@subsection dis


@deftypefn {Library Function} struct unur_par *unur_dis_new( 
double @var{*probabilities}, int @var{plength} )                               ...get default parameters for generator                                      
@end deftypefn     

@deftypefn {Library Function} struct unur_gen *unur_dis_init( 
struct unur_par @var{*parameter} )                                             ...initialize new generator                                                  
@end deftypefn     

@deftypefn {Library Functionint} unur_dis_sample( 
struct unur_gen @var{*generator} )                                             ...sample from generator                            
@end deftypefn
   
@deftypefn {Library Function} void unur_dis_free( 
struct unur_gen @var{*generator} )                                             ...destroy generator object                          
@end deftypefn     


@c cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

@node    Tabl,      Tdr,  Dis,      Methods
@comment node-name, next, previous, up

@subsection tabl

@deftypefn {Library Function} struct unur_par *unur_tabl_new( 
double @var{*pdf}(double @var{x},double @var{*pdf_param}, int @var{n_pdf_params}) )                                                                           ...get default parameters for generator             
@end deftypefn     

@deftypefn {Library Function} struct unur_gen *unur_tabl_init( 
struct unur_par @var{*parameters} )                                            ...initialize new generator                          
@end deftypefn     

@deftypefn {Library Function} double unur_tabl_sample( 
struct @var{unur_gen *generator} )                                             ...sample from generator
@end deftypefn     

@deftypefn {Library Function} double unur_tabl_sample_check( 
struct @var{unur_gen *generator })                                             ...sample from generator                             
@end deftypefn     

@deftypefn {Library Function} void unur_tabl_free( 
struct @var{unur_gen *generator})                                              ...destroy generator object                          
@end deftypefn            


@c cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

@node    Tdr,       Rect, Tabl,     Methods
@comment node-name, next, previous, up

@subsection tdr


@deftypefn {Library Function} struct unur_par *unur_tdr_new( 
double @var{*pdf}(double @var{x},double @var{*pdf_param}, int @var{n_pdf_params}),                                                                            double @var{*dpdf}(double @var{x},double @var{*pdf_param}, int @var{n_pdf_params}) )                                                                          ...get default parameters for generator
@end deftypefn            
@ifhtml
<a href= "file:///home/eeyore/staff/mts/local/unuran-0.0.2-jl/doc/unuran-ref.html#SEC40">unif</a href>
@end ifhtml


@deftypefn {Library Function} struct unur_gen *unur_tdr_init( 
struct unur_par @var{*parameters} )                                            ...initialize new generator                          
@end deftypefn            

@deftypefn {Library Function} double unur_tdr_sample_log( struct @var{unur_gen *gen} );
...sample from generator
@end deftypefn            

@deftypefn {Library Function} double unur_tdr_sample_sqrt( 
struct unur_gen @var{*gen} )                                                   ...sample from generator
@end deftypefn            

@deftypefn {Library Function} double unur_tdr_sample_check( 
struct unur_gen @var{*generator} )                                             ...sample from generator                                                     
@end deftypefn            

@deftypefn {Library Function} void unur_tdr_free( 
struct unur_gen @var{*generator})                                              ...destroy generator object                          
@end deftypefn            
   

@c cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

@node    Rect,      Unif, Tdr ,  Methods
@comment node-name, next, previous, up

@subsection rect


@deftypefn {Library Function} struct unur_par *unru_rect_new( 
int @var{dim} )                                                                ...get default parameters for generator              
@end deftypefn            

@deftypefn {Library Function} struct unur_gen *unur_rect_init( 
struct unur_par @var{*parameters} )                                            ...initialize new generator
@end deftypefn            

@deftypefn {Library Function} void unur_rect_sample_vec( 
struct unur_gen @var{*gen}, double @var{*vec} )                                ...sample from generator
@end deftypefn            

@deftypefn {Library Function} void unur_rect_free ( 
struct unur_gen @var{*generator} )                                             ...destroy generator 
@end deftypefn


@c cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

@node    Unif,      Utdr, Rect,     Methods
@comment node-name, next, previous, up

@subsection unif



@deftypefn {Library Function} struct unur_par *unur_unif_new( 
int @var{start}, int @var{skip} )                                              ...get default parameters for generator              
@end deftypefn            

@deftypefn {Library Function} struct unur_gen *unur_unif_init( 
struct unur_par @var{*parameters} )                                            ...initialize new generator
@end deftypefn            

@deftypefn {Library Function} double unur_unif_sample( 
struct unur_gen @var{*generator} )                                             ...sample from generator
@end deftypefn            

@deftypefn {Library Function} void unur_unif_free( 
struct unur_gen @var{*generator} )                                             ...destroy generator object                  
@end deftypefn            


@c cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

@node    Utdr,      Set,  Unif,     Methods
@comment node-name, next, previous, up

@subsection utdr


@deftypefn {Library Function} struct unur_par *unur_utdr_new( 
double @var{*pdf}(double @var{x},double @var{*pdf_param}, int @var{n_pdf_params}),                                                                            double @var{mode})                                                             ...get default parameters for generator             
@end deftypefn            

@deftypefn {Library Function} struct unur_gen *unur_utdr_init( 
struct unur_par @var{*parameters} )                                            ...initialize new generator                          
@end deftypefn            

@deftypefn {Library Function} double unur_utdr_sample( 
struct unur_gen @var{*generator} )                                             ...sample from generator
@end deftypefn            

@deftypefn {Library Function} double unur_utdr_sample_check( 
struct unur_gen @var{*generator} )                                             ...sample from generator
@end deftypefn            

@deftypefn {Library Function} void unur_utdr_free( 
struct unur_gen @var{*generator})                                              ...destroy generator object                          
@end deftypefn            
   



@c cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

@node    Set,       Stdgen, Utdr,     Methods
@comment node-name, next,   previous, up

@subsection set

@ifhtml
<h3>
@end ifhtml
Parameters for the distribution and its p.d.f.:
@ifhtml
</h3><p></p>
@end ifhtml

@deftypefn {Library Function} int unur_set_domain( 
struct unur_par @var{*parameter}, double @var{left}, double @var{right} )      ...set the left and right borders of the domain of the distribution          
@end deftypefn            

@deftypefn {Library Function} int unur_set_domain_vec( 
struct unur_par @var{*par}, double @var{**domain} )                            ...set coordinates for domain boundary                                       
@end deftypefn            

@deftypefn {Library Function} int unur_set_pdf_param(  
struct unur_par @var{*parameter}, double @var{*pdf_params}, int @var{n_params} )                                                                              ...set array of parameters for p.d.f.                                        
@end deftypefn            

@deftypefn {Library Function} int unur_set_mode( 
struct unur_par @var{*parameter}, double @var{mode} )                          ...set mode of p.d.f.                                                        
@end deftypefn            

@deftypefn {Library Function} int unur_set_pdf_area( 
struct unur_par @var{*parameter}, double @var{area} )                          ...set the (approximate) area below the pdf (default value 1.)               
@end deftypefn            

@ifhtml
<h3><p></p><p></p>
@end ifhtml
Parameters for generators of univariate discrete distributions:            
@ifhtml
</h3><p></p>
@end ifhtml


@deftypefn {Library Function} int unur_set_factor( 
struct unur_par @var{*parameter}, double @var{factor} )                        ...set factor for relative size of (search|guide|alias) table                
@end deftypefn            

@ifhtml
<h3><p></p><p></p>
@end ifhtml
Parameters for generators of univariate continuous distributions:          
@ifhtml
</h3><p></p>
@end ifhtml

@deftypefn {Library Function} int unur_set_cpoints( struct unur_par @var{*parameter}, int @var{n_stp}, double @var{*starting_cpoints} )                       ...set construction points for hat and/or its number for initialization      
@end deftypefn            

@deftypefn {Library Function} int unur_set_max_ratio( 
struct unur_par @var{*parameter}, double @var{max_ratio} )                     ...set bound for ratio A(squeeze) / A(hat)                                   
@end deftypefn            

@deftypefn {Library Function} int unur_set_max_intervals( 
struct unur_par @var{*parameter}, int @var{max_ivs} )                          ...set maximum number of intervals or segments                               
@end deftypefn            

@deftypefn {Library Function} int unur_set_tdr_c( 
struct unur_par @var{*par}, double @var{c} )                                   ...set parameter c for transformation T_c  (method TDR only)                 
@end deftypefn            

@deftypefn {Library Function} int unur_set_tabl_c( struct @var{unur_par *par}, double @var{c} );
...set parameter for equal area rule  (method TABL only)                     
@end deftypefn            

@deftypefn {Library Function} int unur_set_slopes( 
struct unur_par @var{*par}, double @var{*slopes}, int @var{n_slopes} )         ...set slopes of p.d.f. (method TABL only)                                   
@end deftypefn            

@ifhtml
<h3><p></p><p></p>
@end ifhtml
Parameters for generators of mulitvariate continuous distributions:       
@ifhtml
</h3><p></p>
@end ifhtml

@deftypefn {Library Function} int unur_get_dimension( 
struct unur_gen @var{*gen} )
@end deftypefn            

@ifhtml
<h3><p></p><p></p>
@end ifhtml
Parameters for all generators:                                             
@ifhtml
</h3><p></p>
@end ifhtml

@deftypefn {Library Function} int unur_set_urng( 
struct unur_par @var{*par}, UNUR_URNG_TYPE @var{urng} )                        ...set uniform random number generator                                       
@end deftypefn            

@deftypefn {Library Function} UNUR_URNG_TYPE unur_chg_urng( 
struct unur_gen @var{*gen}, UNUR_URNG_TYPE @var{urng} )                        ...change uniform random number generator                                    
@end deftypefn            

@deftypefn {Library Function} UNUR_URNG_TYPE unur_get_urng( 
struct unur_gen @var{*gen} )                                                   ...get uniform random number generator                                    
@end deftypefn            

@deftypefn {Library Function} int unur_set_variant( 
struct unur_par @var{*par}, unsigned long @var{variant} )                      ...set variant of method                                                     
@end deftypefn            

@deftypefn {Library Function} int unur_set_check(  
struct unur_par @var{*parameter}, int @var{check} )                            ...turn testing of sampling on/off 
@end deftypefn            

@deftypefn {Library Function} int unur_set_copyall(  
struct unur_par @var{*par}, int @var{copy} )                                   ...turn copaing of all inputs into generator object on/off  
@end deftypefn            

@deftypefn {Library Function} int unur_set_debug( 
struct unur_par @var{*parameter}, unsigned long @var{db} )                     ...set debugging flag for generator                                          
@end deftypefn            

@ifhtml
<h3><p></p><p></p>
@end ifhtml
Parameters for debugging (defined in debug.c):                             
@ifhtml
</h3><p></p>
@end ifhtml

@deftypefn {Library Function} FILE* unur_set_log(FILE @var{*log})
@end deftypefn            

@deftypefn {Library Function} FILE* unur_get_log(void)
@end deftypefn            
    

@c cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

@node    Stdgen ,   Tests , Set,      Function Calls
@comment node-name, next,   previous, up


@section stdgen


@deftypefn {Library Function} double nbm( 
UNUR_URNG_TYPE  @var{urng})                                                    ...normal distribution 
@end deftypefn            

@deftypefn {Library Function} double gammarand(  
double @var{a}, UNUR_URNG_TYPE  @var{urng} )                                   ...gamma distribution
@end deftypefn            



@c cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

@node    Tests ,    Utils , Stdgen,      Function Calls
@comment node-name, next,   previous,    up


@section tests

@ifhtml
<h4>
@end ifhtml
run battery of tests:                                                   
@ifhtml
<p></h4></p>
@end ifhtml
   
@deftypefn {Library Function} void unur_run_tests( 
struct unur_par @var{*par}, unsigned long @var{tests},                         double @var{*cdf}(double @var{x}, double @var{*fparam}, int @var{n_fparam}))
@end deftypefn            

@ifhtml
<h4>
@end ifhtml
particular tests:                                                         
@ifhtml
<p></h4></p>
@end ifhtml

@deftypefn {Library Function} void unur_test_printsample( 
struct unur_gen @var{*gen}, int @var{n_rows}, int @var{n_cols} )               ... print a sample
@end deftypefn            

@deftypefn {Library Function} struct unur_gen *unur_test_timing( 
struct unur_par @var{*par}, int @var{log_samplesize} )                         ...timing
@end deftypefn            
         
@deftypefn {Library Function} int unur_test_count_urn( 
struct unur_gen @var{*gen}, int @var{samplesize} )                             ...count used uniform random numbers
@end deftypefn            

@deftypefn {Library Function} double unur_test_chi2( 
struct unur_gen @var{*gen},                                               double @var{*cdf}(double @var{x}, double @var{*fparam}, int @var{n_fparam}),            int @var{intervals},                                                      int @var{samplesize},                                                    int @var{classmin},                                                      int @var{output} )                                                       ...chi^2 tests
@end deftypefn            

@deftypefn {Library Function} int unur_make_scatterplot( 
struct unur_gen @var{*gen},                                               double @var{*cdf}(double @var{x}, double @var{*fparam}, int @var{n_fparam}))        ...make scatterplot of generated numbers
@end deftypefn            

@deftypefn {Library Function} double _unur_sample_cont_transformed( 
struct unur_gen @var{*gen},                                               double @var{*cdf}(double @var{x}, double @var{*fparam}, int @var{n_fparam}) )       ...sample from generator and transform to uniform by means of the c.d.f.
@end deftypefn            
  
@c cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

@node    Utils ,    Continuous Distribution , Tests,    Function Calls
@comment node-name, next,                     previous, up


@section utils

@ifhtml
<h4>
@end ifhtml
allocate memory :
@ifhtml
<p></h4></p>
@end ifhtml

@deftypefn {Library Function} void* _unur_malloc(size_t size);
@end deftypefn            

@ifhtml
<p></p><h4><p></p>
@end ifhtml
debugging tools:
@ifhtml
<p></h4></p>
@end ifhtml

@deftypefn {Library Function} char* _unur_make_genid(
char @var{*gentype})
@end deftypefn            

@deftypefn {Library Function} void  _unur_db_error( 
char @var{*genid},                                                        int @var{errortype},                                                     char @var{*msg},                                                         char @var{*filename},                                                    int @var{line})
@end deftypefn            

@deftypefn {Library Function} void  _unur_db_warning(
char @var{*genid},                                                        int @var{errortype},                                                     char @var{*msg},                                                         char @var{*filename},                                                    int @var{line})
@end deftypefn            

@deftypefn {Library Function} void  _unur_db_cookie_warning( 
unsigned long @var{expected},                                             unsigned long @var{observed},                                            char @var{*filename},                                                    int @var{line})
@end deftypefn            

@ifhtml
<p></p><h4><p></p>
@end ifhtml
miscellaneous:                                                  
@ifhtml
<p></h4></p>
@end ifhtml

@deftypefn {Library Function} double _unur_arcmean( 
double @var{x0},                                                          double @var{x1} )
@end deftypefn               


















