\input texinfo   @c -*-texinfo-*-

@c %**start of header
@setfilename unuran-ref.info
@settitle    UNURAN User Manual
@iftex
@afourpaper
@end iftex
@c %**end of header

@dircategory Scientific software
@direntry
* unuran-ref: (unuran-ref).  UNURAN -- Universal Non-Uniform Random number generator
@end direntry

@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
@c
@c Include macros ...
@c

@tex
@include tex_macros.tex              
@end tex

@setchapternewpage odd

@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
@c
@c Version ...
@c

@include version.texi

@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
@c
@c Title page and copyright ...
@c

@include title.texi

@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
@c
@c `Top' Node and Master Menu
@c
     
@node    Top,       Introduction, (dir),    (dir)
@comment node-name, next,          previous, up

@menu
@c  * Copying::          Your rights and freedoms.
* Introduction::         This chapter contains the file unuran-ref2.texi.
* Distribution Library:: This chapter contains a library of 
* Function Calls::       The implemented functions are described here.
* Concept Index::        This index has two entries.
@end menu



@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
@c
@c The Body of the Document
@c


@node    Introduction, Routines for User , Top,      Top
@comment node-name,    next,               previous, up
     
@menu
@c  * Copying::             Your rights and freedoms.
* Routines for User::       The function syntax used in the user
                            interface is described here.
* Example::                 This chaper provides a short demo program.
@end menu

@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
@c
@c Introduction ...
@c

@include intro.texi

@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
@c
@c Distributions ...
@c

@include distr.texi

@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
@c
@c Routines
@c

@include routines.texi


@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
@c
@c The End of the Document
@c

@node    Concept Index,    ,  Discrete Distribution, Top
@comment node-name,    next,  previous,              up
@unnumbered Concept Index

@printindex cp
@contents

@bye












