\input texinfo   @c -*-texinfo-*-

@c $Id: unuran.texi 3564 2007-04-18 06:32:53Z leydold $

@c %**start of header
@setfilename unuran_win32.info
@settitle    Using UNU.RAN with Microsoft Visual C
@iftex
@afourpaper
@end iftex
@footnotestyle end
@setchapternewpage odd
@c %**end of header

@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
@c 
@c Some data about this software
@c 

@dircategory Scientific software
@direntry
* unuran_win32: (unuran_win32).  Using UNU.RAN with Microsoft Visual C
@end direntry

@c Version ...
@include version_win32.texi
@include unuran_win32_libname.texi

@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
@c 
@c Copyright
@c 

@copying
@noindent
Copyright @copyright{} 2000--2007 Institut fuer Statistik, WU Wien.

@noindent
Permission is granted to make and distribute verbatim
copies of this manual provided the copyright notice and
this permission notice are preserved on all copies.
@end copying

@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
@c 
@c Titlepage ...
@c 

@titlepage
@title{Using UNU.RAN with Microsoft Visual C}
@subtitle{UNU.RAN -- Universal Non-Uniform RANdom number generators}
@subtitle Version @value{VERSION}, @value{UPDATED}

@author Josef Leydold
@author Wolfgang H@"ormann
@author Engin Durmaz

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
@c 
@c Table of contents 
@c [ disabled ]
@c 

@c @contents

@c ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
@c 
@c insert automatically generated documentation ...
@c 

@node TOP
@top  Using UNU.RAN with Microsoft Visual C

@menu
* Folder:: UNU.RAN Installation Folder
* Project:: Building Your Own Project which Links with UNU.RAN
@end menu

@ifinfo
@noindent
This is the online-documentation of UNU.RAN.@*
Version: @value{VERSION}@*
Date: @value{UPDATED}
@end ifinfo

This document describes how to use Microsoft Visual Studio to
create a C or C++ project and link the target with UNU.RAN.

@uref{http://statmath.wu-wien.ac.at/unuran,UNU.RAN}
(Universal Non-Uniform RAndom Number generator) is
a collection of algorithms for generating non-uniform
pseudorandom variates as a library of C functions
designed and implemented by the 
@uref{http://statmath.wu-wien.ac.at/arvag,ARVAG}
(Automatic Random VAriate Generation) project group in Vienna, and
released under the GNU Public License (GPL).

@c --------------------------------------------------------------------

@node Folder, , TOP, TOP
@section  UNU.RAN Installation Folder

Throughout this document, the UNU.RAN installation folder is referred
to as @file{<UNURANDIR>}. 
For example, if UNU.RAN has been installed in the folder
@file{C:\libunurandll}, references to @file{<UNURANDIR>/win32}
represent @file{C:\libunurandll\win32}.

@c --------------------------------------------------------------------

@node Project, , TOP, TOP
@section  Building Your Own Project which Links with UNU.RAN

@emph{Note:} 
The information below applies to the Visual C++ .NET 2005.

@sp 1

Let us assume that you want to build a target named
@file{example.exe} and have:

@itemize
@item 
a source file named @file{example.c} which uses the C API of the
UNU.RAN library;
@item
a folder where this file is located and which we refer to as
@file{<MYAPPDIR>}.
@end itemize

One way to build your project is to create a @emph{Solution} named
@file{example.sln} as described here.

@enumerate
@item
Start Microsoft Visual Studio .NET 2005.

@item
Build the @file{example.sln} solution: 

@sp 1

From the @file{File} menu, select @file{New->}, and then
@file{Project}.

@sp 1
When the @file{New Project} dialog box appears then

@itemize @minus
@item
In the @file{Project Types} pane, select @file{Visual C++ Projects}.
@item
In the @file{Templates pane}, select the @file{Win32 Project} icon.
@item
Fill in the project name (@samp{example}).
@item
If necessary, correct the location of the project (to
@file{<MYAPPDIR>}).
@item
Click @file{OK}.
@end itemize

When the Win32 Application Wizard appears then

@itemize @minus
@item
Click on @file{Application Settings}.
@item
Select @file{Console Application} as Application type.
@item
Make sure that @file{Empty project} is checked in @file{Additional
Options}.
@item
Click @file{Finish}.
@end itemize

This creates a solution, @file{example}, with a single project,
@file{example}. You can view the contents of the solution by selecting
@file{Solution Explorer} in the @file{View} menu.

@item
Add your source file to the project. 
From the @file{Project} menu, choose @file{Add Existing Item}:

@itemize @minus
@item
Move to folder @file{<MYAPPDIR>} and select @file{example.c}.
@item
Click @file{Open}.
@end itemize

@item
Set some options so that the project knows where to find the UNU.RAN
include files and the UNU.RAN libraries.

@itemize @minus
@item
From the @file{Project} menu, choose example @file{Properties}.
The example @file{Property Pages} dialog box appears.
@item
In the @file{Configuration} drop-down list, select @file{Release}.
@item
Select @file{C/C++} in the @file{Configuration Properties} tree.
@item
Select @file{General}.
@item
In the @file{Additional Include Directories} field, add the
directories
@itemize .
@item
@file{<UNURANDIR>\win32}.
@item
Choose @file{No} for @file{Detect 64-bit Portability Issues}.
@end itemize
@item
Select @file{Linker} in the @file{Configuration Properties} tree.
@itemize .
@item
Select @file{General} and then select @file{Additional Library
Directories}.
@item
Add directory @file{<UNURANDIR>\win32}.
@item
Select @file{Input} and then select @file{Additional Dependencies}.
Add library file @file{@value{LIBUNURAN}.lib}.
@end itemize
@item
Click @file{OK} to close the example @file{Property Pages} dialog box.
@end itemize

@item 
Set the default project configuration.

@itemize @minus
@item
From the @file{Build} menu, select @file{Configuration Manager}.
@item
Select @file{Release} in the @file{Active Solution Configuration}
drop-down list.
@item
Click @file{Close}.
@end itemize

@item
Next, you have to locate the @file{@value{LIBUNURAN}.dll} file into
@file{<MYAPPDIR>\example}, or you have to adjust the @env{PATH}
environmental variable for the dll.

@item
Finally, to build the project, from the @file{Build} menu, select
@file{Build Solution}.

@end enumerate

After completion of the compiling and linking process, the target is
created. The full path of the test.exe is
@file{<MYAPPDIR>\example\Release\example.exe}. Notice that, if you
want to run the @file{example.exe} by clicking on it, you need to
locate the dll file in the same directory.

@c --------------------------------------------------------------------
@bye
